apps/main_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.log_register, name="register"),
    url(r'^login$', views.log_register, name="login"),
    url(r'^travels$', views.travels, name="travels"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^travels/add/$', views.addtrip, name="addtrip"),
    url(r'^createtrip$', views.createtrip, name="createtrip"),
    #url(r'^travels/add/$', views.addtrip, name="addtrip"),
#    url(r'^otherusertrip$', views.otherusertrip, name="otherusertrip"),
#    url(r'^yourtrips$', views.yourtrips, name="yourtrips"),
#    url(r'^join/(?P<id>\d+)$', views.join, name="join"),
    url(r'^destination/(?P<id>\d+)$', views.destination, name="destination"),
#    url(r'^home$', views.home, name="home"),
  ]

main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.main_app.urls', namespace="main_app")),
]

apps/main_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import bcrypt, re
VALIDREG = re.compile(r'^[a-zA-Z]*$')
DATEREG = re.compile(r'^[0-9]-[0-9]-[0-9]*$')

class UserDBManager(models.Manager):
    def hash_pass(self, password):
        return bcrypt.hashpw(password, bcrypt.gensalt())

    def check_create(self, data):
        errors = []
        if len(data['name']) < 3:
            errors.append(['name', "Name must be at least three characters in length"])
        if len(data['username']) < 3:
            errors.append(['username', "User Name must be at least three characters in length"])
        if len(data['password']) < 8:
            errors.append(['password', "Password must be at lease eight characters in length"])
        if not data['password'] == data['confirmpass']:
            errors.append(['confirmpass', "Passwords do not match"])
        if errors:
            return [False, errors]
        else:
            curent_user = UserDB.objects.filter(username=data['username'])
            if curent_user:
                errors.append(['curent_user', "Unable to register, please use alternate information"])
                return [False, errors]
            newUser = UserDB(name=data['name'], username=data['username'])
            # hashed_pass = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            # print hashed_pass, "hashed password"
            newUser.hashpw = self.hash_pass(data['password'].encode())
            print newUser.hashpw
            newUser.save()
            print newUser
            return [True, newUser]

    def check_log(self, data):
        errors = []
        curent_user = UserDB.objects.filter(username=data['username'])
        if not curent_user:
            errors.append(['account', "UserName or Password incorrect"])
        elif not bcrypt.checkpw(data['password'].encode(), curent_user[0].hashpw.encode()):
            errors.append(['account', "UserName or Password incorrect"])
        if errors:
            return [False, errors]
        else:
            return [True, curent_user[0]]

class UserDB(models.Model):
    name = models.CharField(max_length=50, blank=False)
    username = models.CharField(max_length=50)
    hashpw = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserDBManager()
    def __str__(self):
        return 'ID: %s | Name: %s | UserName: %s | Created: %s | Updated: %s' % (self.id, self.name, self.username, self.created_at, self.updated_at)

class TripDBManager(models.Manager):
    def create_trip(self, data, user):
        print(" I am in create_trip defination")
        newtrip = TripSchedulesDB(destination=data['destination'], description=data['description'], travelstartdate=data['travelstartdate'], travelenddate=data['travelenddate'], user=user)
        newtrip.save()
        print("After saving create trip")
        print newtrip
        return [True, newtrip]

class TripSchedulesDB(models.Model):
    destination = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    travelstartdate = models.DateField()
    travelenddate = models.DateField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user=models.ForeignKey(UserDB, related_name="usertrip")

    objects = TripDBManager()
    def __str__(self):
        return 'ID: %s | Destination: %s | Description: %s | Travelstartdate: %s | Travelenddate: %s | Travelenddate: %s' % (self.id, self.destination, self.description, self.travelstartdate, self.travelenddate, self.user)

class JoinDBManager(models.Manager):
    pass

class JoinsDB(models.Model):
    user_join=models.ForeignKey(UserDB, related_name="user_join")
    trip_join=models.ForeignKey(TripSchedulesDB, related_name="trip_join")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = JoinDBManager()

apps/main_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import UserDB, TripSchedulesDB, JoinsDB

def index(request):
    return render(request, 'main_app/index.html')

def log_register(request):
    if request.method == "POST":
        print request.POST
        if request.POST["submit"] == "register":
            response = UserDB.objects.check_create(request.POST)
        elif request.POST["submit"] == "login":
            response = UserDB.objects.check_log(request.POST)
        if not response[0]:
            for message in response[1]:
                messages.error(request, message[1])
            return redirect('main_app:index')
        else:
            request.session['user'] = {
            "id": response[1].id,
            "name": response[1].name,
            "username": response[1].username,
            }
            return redirect('main_app:travels')
    return redirect('main_app:index')

def logout(request):
    request.session.clear()
    return redirect('main_app:index')

def travels(request):
    curr_id = request.session['user']['id']
    print("FFFFFFFFFFF")
    print curr_id
    yourdata = {
    "yourtrips": TripSchedulesDB.objects.filter(user=UserDB.objects.get(id=curr_id)),
    "otherstrips": TripSchedulesDB.objects.exclude(user=UserDB.objects.get(id=curr_id)),
    }
    print yourdata
    return render(request, 'main_app/travels.html', yourdata)

def addtrip(request):
    return render(request, 'main_app/addtrip.html')

def createtrip(request):
    if request.method == "POST":
        print request.POST
        #if request.POST["submit"] == "addtrip":
        current_user = UserDB.objects.get(id=request.session['user']['id'])
        response = TripSchedulesDB.objects.create_trip(request.POST, current_user)
    return redirect('main_app:travels')

def addtravel(request):
    if request.method == "POST":
        print ("SSSSSSSSS")
        print request.POST
    if request.POST["submit"] == "addtrip":
        response = TripSchedulesDB.objects.create_trip(request.POST)
    if not response[0]:
        for message in response[1]:
            messages.error(request, message[1])
        return redirect('main_app:travels')
    else:
        request.session['trip'] = {
        "id": response[1].id,
        "destination": response[1].destination,
        "description": response[1].description,
        }
        return redirect('main_app:travels')
    return render(request, 'main_app/addtravel.html')

def otherusertrip(request):
    pass

def yourtrip(request):
    yourdata = {
    "trips": TripSchedulesDB.objects.all(),
    }
    print yourdata
    return render(request, 'main_app/travels.html', yourdata)

def join(request, id):
    #return redirect('main_app:travels')
    pass

def destination(request, id):
    tripdata = {
    "dest": TripSchedulesDB.objects.filter(id=id),
    }
    print tripdata
    return render(request, 'main_app/destination.html', tripdata)

def home(request):
    return redirect('main_app:travels')

apps/main_app/templates/main_app/addtrip.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Travels Dashboard</title>
    <link rel="stylesheet" href="{% static 'main_app/css/materialize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/materialize_icons.css' %}">
    <script src="{% static 'main_app/js/jquery-2.2.3.js' %}"></script>
    <script src="{% static 'main_app/js/jquery-ui.js' %}"></script>
    <script src="{% static 'main_app/js/materialize.js' %}"></script>
  </head>
  <body>
    <header class="blue">
      <nav class="blue">
        <ul class="right">
          <li><a href="{% url 'main_app:travels' %}">Home</a></li>
          <li><a href="{% url 'main_app:logout' %}">Logout</a></li>
        </ul>
      </nav>
    </header>
    <h4>Add a Trip</h4>
    <main class="container section">
      {% if messages %}
      <div class="row">
      {% for message in messages %}
      <p class="red white-text col s6 offset-s3">{{message}}</p>
      {% endfor %}
      {% endif %}
      <section class="row">
        <form class="col s6" action="{% url 'main_app:createtrip' %}" method="post">
          {% csrf_token %}
          Destination: <input type="text" name="destination" placeholder="Please Enter Destination">
          Description: <input type="text" name="description" placeholder="Please Enter Description">
          Travel Date From: <input type="date" name="travelstartdate" placeholder="Please Enter Travel Start Date">
          Travel Date End: <input type="date" name="travelenddate" placeholder="Please Enter Travel End Date">
          <button type="submit" name="submit" value="addtrip" class="btn">Add</button>
        </form>
      </section>
    </main>
  </body>
</html>

apps/main_app/templates/main_app/destination.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Travels Dashboard</title>
    <link rel="stylesheet" href="{% static 'main_app/css/materialize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/materialize_icons.css' %}">
    <script src="{% static 'main_app/js/jquery-2.2.3.js' %}"></script>
    <script src="{% static 'main_app/js/jquery-ui.js' %}"></script>
    <script src="{% static 'main_app/js/materialize.js' %}"></script>
  </head>
  <body>
    <header class="orange">
      <nav class="orange">
        <ul class="right">
          <li><a href="{% url 'main_app:travels' %}">Home</a></li>
          <li><a href="{% url 'main_app:logout' %}">Logout</a></li>
        </ul>
      </nav>
    </header>
    <h4>{{dest}}</h4>
    <main class="container section">
      {% if messages %}
      <div class="row">
      {% for message in messages %}
      <p class="red white-text col s6 offset-s3">{{message}}</p>
      {% endfor %}
      {% endif %}
      <section class="row">
        <p>{{trip.destination}}</p>
      </section>
    </main>
  </body>
</html>

apps/main_app/templates/main_app/index.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Log and Registration</title>
    <link rel="stylesheet" href="{% static 'main_app/css/materialize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/materialize_icons.css' %}">
    <script src="{% static 'main_app/js/jquery-2.2.3.js' %}"></script>
    <script src="{% static 'main_app/js/jquery-ui.js' %}"></script>
    <script src="{% static 'main_app/js/materialize.js' %}"></script>
  </head>
  <body>
    <header class="green">
      <nav class="green">
        <a class="brand-logo" href="#">Welcome to Loging and Registration</a>
      </nav>
    </header>
    <main class="container section">
      {% if messages %}
      <div class="row">
      {% for message in messages %}
      <p class="red white-text col s6 offset-s3">{{message}}</p>
      {% endfor %}
      {% endif %}
      <section class="row">
        <form class="col s6" action="{% url 'main_app:register' %}" method="post">
          {% csrf_token %}
          <input type="text" name="name" placeholder="Your Full Name">
          <input type="text" name="username" placeholder="Select a User Name">
          <input type="password" name="password" placeholder="Password ********">
          <input type="password" name="confirmpass" placeholder="Confirm Password">
          <button type="submit" name="submit" value="register" class="btn">Register</button>
        </form>
        <form class="col s6" action="{% url 'main_app:login' %}" method="post">
          {% csrf_token %}
          <input type="text" name="username" placeholder="Please Enter your Username">
          <input type="password" name="password" placeholder="Password ********">
          <button type="submit" name="submit" value="login" class="btn">Login</button>
        </form>
      </section>
    </main>
  </body>
</html>

apps/main_app/templates/main_app/travels.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <title>Travels Dashboard</title>
    <link rel="stylesheet" href="{% static 'main_app/css/materialize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main_app/css/materialize_icons.css' %}">
    <script src="{% static 'main_app/js/jquery-2.2.3.js' %}"></script>
    <script src="{% static 'main_app/js/jquery-ui.js' %}"></script>
    <script src="{% static 'main_app/js/materialize.js' %}"></script>
  </head>
  <body>
    <nav class="orange">
      <ul class="right">
        <li><a href="{% url 'main_app:logout' %}">Logout</a></li>
      </ul>
    </nav>
    <main class="container">
      <h3>Hello {{request.session.user.name}}</h3>
    </main>

    <h5>Your trip schedules</h5>
    <main class="container section">
      {% if messages %}
      <div class="row">
      {% for message in messages %}
      <p class="red white-text col s6 offset-s3">{{message}}</p>
      {% endfor %}
      {% endif %}
      <section class="row">
          <table>
            <thead>
              <tr>
                <th>Destination</th>
                <th>Travel Start Date</th>
                <th>Travel End date</th>
                <th>Plan</th>
              </tr>
            </thead>
            <tbody>
              {% if yourtrips %}
              {% for yourtrips in yourtrips %}
              <tr>
                <td><a href="/destination/{{yourtrips.id}}">{{yourtrips.destination}}</a></td>
                <td>{{yourtrips.startdate}}</td>
                <td>{{yourtrips.enddate}}</td>
                <td>{{yourtrips.description}}</td>
              </tr>
              {% endfor %}
              {% endif %}
            </tbody>
          </table>
          <h5>Other Users travel plan</h5>
          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Destination</th>
                <th>Travel Start Date</th>
                <th>Travel End date</th>
                <th>Join</th>
              </tr>
            </thead>
            <tbody>
              {% if otherstrips %}
              {% for otherstrips in otherstrips %}
              <tr>
                <td>{{otherstrips.UserName}}</td>
                <td><a href="/destination/{{otherstrips.id}}">{{otherstrips.destination}}</a></td>
                <td>{{otherstrips.startdate}}</td>
                <td>{{otherstrips.enddate}}</td>
                <td><a href="">Join</a></td>
              </tr>
              {% endfor %}
              {% endif %}
            </tbody>
          </table>
          <h4><p align="right"><a href="travels/add">Add Travel Plan</a></p></h4>
      </section>
    </main>
  </body>
</html>